# versin: '3'

# services:
#   telebot:
#     build: .
#     container_name: telebot
#     command: python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"

#   pgdb:
#     image: postgres
    